name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests and Generate Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install jq and bc
        run: sudo apt-get install -y jq bc

      - name: Run Tests with Coverage
        run: |
          npx nyc --reporter=json-summary --reporter=text npx playwright test

      - name: Upload HTML Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-summary
          path: coverage/coverage-summary.json

      - name: Update coverage
        run: |
          coverage=$(jq '.total.lines.pct' coverage/coverage-summary.json)
          color=$(echo "$coverage < 80" | bc -l | awk '{if ($1) print "red"; else print "green"}')
          curl -s -X POST "https://badge.cs329.click/badge/${{ github.repository_owner }}/jwtpizzacoverage?label=Coverage&value=$coverage%25&color=$color" \
            -H "authorization: bearer ${{ secrets.FACTORY_API_KEY }}" \
            -o /dev/null
